"""Add Google OAuth fields

Revision ID: 60922c1878a6
Revises: 
Create Date: 2025-05-26 07:30:37.624799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60922c1878a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('google_email', sa.String(length=120), nullable=True))
        batch_op.create_unique_constraint('uq_user_google_id', ['google_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_google_id', type_='unique')
        batch_op.drop_column('google_email')
        batch_op.drop_column('google_id')

    # ### end Alembic commands ###
